badoo/RIBs

android/libraries/rib-android/build.gradle
android/libraries/rib-android/gradle.properties

Publish rib-android

---

android/tooling/rib-intellij-plugin/src/main/java/com/badoo/ribs/plugin/generator/SourceSetDirectoriesProvider.kt
android/tooling/rib-intellij-plugin/src/main/java/com/badoo/ribs/plugin/rename/RenameRibDialog.kt

Use package psi node as a root for renamings

---

.travis.yml

Disable instrumentation tests on CI

---

android/tutorials/tutorial3/README.md

few lines are out of sync with the tutorial code

Update Readme.md for Tutorial 3

---

android/tutorials/tutorial4/README.md

Fix wrong class name in tutorial 4 (fixes #99)

---

android/gradle.properties
android/gradle/dependencies.gradle
android/tooling/rib-intellij-plugin/build.gradle
android/tooling/rib-intellij-plugin/src/main/java/com/badoo/ribs/plugin/action/GenerateTemplateAction.kt
android/tooling/rib-intellij-plugin/src/main/java/com/badoo/ribs/plugin/generator/SourceSetDirectoriesProvider.kt
android/tooling/rib-intellij-plugin/src/main/java/com/badoo/ribs/plugin/icons/RIBIconProvider.kt
android/tooling/rib-intellij-plugin/src/main/java/com/badoo/ribs/plugin/icons/RibIconProvider.kt
android/tooling/rib-intellij-plugin/src/main/java/com/badoo/ribs/plugin/index/RibIndexer.kt
android/tooling/rib-intellij-plugin/src/main/java/com/badoo/ribs/plugin/util/IndexUtils.kt
android/tooling/rib-intellij-plugin/src/main/resources/META-INF/plugin.xml

Fixed usages of removed `AndroidFacet` api. Seems to be backwards compatible.

Android Studio 4.0 plugin fix

---

android/gradle/dependencies.gradle

Update MVICore to the latest version

---

android/gradle/dependencies.gradle

Update Kotlin to 1.3.60

---

android/tutorials/tutorial3/README.md
android/tutorials/tutorial3/solutions.md
android/tutorials/tutorial4/README.md

Tutorials clarification and typo correction

---

android/libraries/rib-base/src/main/java/com/badoo/ribs/android/recyclerview/RecyclerViewHostFeature.kt
android/libraries/rib-base/src/main/java/com/badoo/ribs/core/routing/configuration/ConfigurationCommandCreator.kt
android/libraries/rib-base/src/main/java/com/badoo/ribs/core/routing/configuration/ConfigurationKey.kt
android/libraries/rib-base/src/main/java/com/badoo/ribs/core/routing/configuration/Transaction.kt
android/libraries/rib-base/src/test/java/com/badoo/ribs/core/routing/configuration/ConfigurationFeatureTest.kt
android/libraries/rib-base/src/test/java/com/badoo/ribs/core/routing/configuration/ConnectorCommandCreatorTest.kt

Adding unique payload to ConfigurationKey to avoid map key collision by position only.

Fix replace

---

.github/workflows/ci.yml

Added simple CI workflow config for Github Actions to execute:
1. Assemble project
1. Run Detekt
1. Run Unit Test
1. Run UI tests on 21,29 sdk emulators
[Sample run](https://github.com/antonshilov/RIBs/actions/runs/71631724)
**Possible improvements to add later:**
- Store Gradle caches
- Upload build artifacts(jars, test reports)
- Integrate with [Danger](https://github.com/danger/danger) to send additional messages about build issues to the PRs
Fixes #74

Add github actions ci workflow

---

.github/workflows/ci.yml

Increased unit test job timeout to 20 mins

Increase unit tests timeout

---

android/app-example/src/main/java/com/badoo/ribs/example/rib/big/BigView.kt
android/app-example/src/main/java/com/badoo/ribs/example/rib/hello_world/HelloWorldView.kt
android/app-example/src/main/java/com/badoo/ribs/example/rib/menu/MenuBuilder.kt
android/app-example/src/main/java/com/badoo/ribs/example/rib/menu/MenuNode.kt
android/app-example/src/main/java/com/badoo/ribs/example/rib/switcher/SwitcherView.kt
android/app-example/src/test/java/com/badoo/ribs/example/rib/switcher/SwitcherRouterTest.kt
android/app-example/src/test/java/com/badoo/ribs/example/rib/switcher/SwitcherWorkflowTest.kt
android/libraries/rib-base/src/androidTest/java/com/badoo/ribs/test/util/ribs/root/TestRoot.kt
android/libraries/rib-base/src/main/java/com/badoo/ribs/core/Rib.kt
android/libraries/rib-base/src/main/java/com/badoo/ribs/core/builder/BuildParams.kt
android/libraries/rib-base/src/main/java/com/badoo/ribs/core/builder/Builder.kt
android/libraries/rib-base/src/main/java/com/badoo/ribs/core/builder/SimpleBuilder.kt
android/libraries/rib-base/src/test/java/com/badoo/ribs/core/helper/TestBuildParams.kt
android/templates/snapshot/src/main/java/com/badoo/ribs/template/node_dagger_build_param/foo_bar/builder/FooBarBuilder.kt

Remove identifier object

---

android/libraries/rib-base/src/main/java/com/badoo/ribs/core/routing/transition/progress/SingleProgressEvaluator.kt
android/libraries/rib-base/src/main/java/com/badoo/ribs/util/RIBs.kt

Encountered as a corner case during development
Added more info and routed it through error handler

Handle animation state inconsistency through error handler

---

android/app-example/README.md
android/app-example/api.properties
android/app-example/build.gradle
android/app-example/src/main/AndroidManifest.xml
android/app-example/src/main/java/com/badoo/ribs/example/RootActivity.kt
android/app-example/src/main/java/com/badoo/ribs/example/network/ApiFactory.kt
android/app-example/src/main/java/com/badoo/ribs/example/network/AuthInterceptor.kt
android/app-example/src/main/java/com/badoo/ribs/example/network/UnsplashApi.kt
android/app-example/src/main/java/com/badoo/ribs/example/network/model/AccessToken.kt
android/app-example/src/main/java/com/badoo/ribs/example/network/model/Collection.kt
android/app-example/src/main/java/com/badoo/ribs/example/network/model/Links.kt
android/app-example/src/main/java/com/badoo/ribs/example/network/model/Photo.kt
android/app-example/src/main/java/com/badoo/ribs/example/network/model/SearchResult.kt
android/app-example/src/main/java/com/badoo/ribs/example/network/model/Urls.kt
android/app-example/src/main/java/com/badoo/ribs/example/network/model/User.kt
android/gradle/dependencies.gradle

Add unsplash api client

---

android/app-example/build.gradle
android/app-example/src/main/java/com/badoo/ribs/example/auth/AuthConfig.kt
android/app-example/src/main/java/com/badoo/ribs/example/auth/AuthDataSource.kt
android/app-example/src/main/java/com/badoo/ribs/example/auth/AuthState.kt
android/app-example/src/main/java/com/badoo/ribs/example/auth/AuthStateStorage.kt
android/app-example/src/main/java/com/badoo/ribs/example/network/UnsplashApi.kt
android/app-example/src/test/java/com/badoo/ribs/example/auth/AuthDataSourceImplTest.kt

Added auth datasource
Closes #184

Added auth data source

---

app-example/src/main/java/com/badoo/ribs/example/extensions/RibView.kt
app-example/src/main/java/com/badoo/ribs/example/logged_out_container/LoggedOutContainerBuilder.kt
app-example/src/main/java/com/badoo/ribs/example/logged_out_container/LoggedOutContainerInteractor.kt
app-example/src/main/java/com/badoo/ribs/example/logged_out_container/routing/LoggedOutContainerChildBuilders.kt
app-example/src/main/java/com/badoo/ribs/example/logged_out_container/routing/LoggedOutContainerRouter.kt
app-example/src/main/java/com/badoo/ribs/example/welcome/Welcome.kt
app-example/src/main/java/com/badoo/ribs/example/welcome/WelcomeBuilder.kt
app-example/src/main/java/com/badoo/ribs/example/welcome/WelcomeInteractor.kt
app-example/src/main/java/com/badoo/ribs/example/welcome/WelcomeNode.kt
app-example/src/main/java/com/badoo/ribs/example/welcome/WelcomeView.kt
app-example/src/main/java/com/badoo/ribs/example/welcome/mapper/ViewEventToOutput.kt
app-example/src/main/res/layout/rib_welcome.xml
app-example/src/main/res/values/strings.xml
app-example/src/test/java/com/badoo/ribs/example/welcome/WelcomeInteractorTest.kt
libraries/rib-base-test/src/main/java/com/badoo/common/ribs/InteractorTestHelper.kt

Added Welcome rib, mockIO method to the InteractorTestHelper

Add welcome rib

---

libraries/rib-base/src/main/java/com/badoo/ribs/android/dialog/Dialog.kt

Problem:
You can't override way how to show dialogs. Because buttons was hidden from client code you didn't have possibility to override UI how to show it.

Make dialog buttons open

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Update gradle version to fix ci

---

libraries/rib-portal-rx/gradle.properties
libraries/rib-portal/gradle.properties
libraries/rib-recyclerview/gradle.properties

**Description**: Added remaining gradle.properties to ensure all artifacts are published

Added remaining gradle.properties for artifact publishing

---

gradle/dependencies.gradle

To use `fun interfaces` [here](https://github.com/badoo/RIBs/pull/268/files#diff-d49092e098768be6a8955b8eb7e25231e19dc903ae4ace367d799f74a7a151f0R6) and in other parts of the framework.

Use Kotlin 1.4.31

---

.github/workflows/ci.yml

Uploading the instrumentation test results as part of the workflow so that it is easier to determine why the tests have failed.

Upload instrumentation test reports to github actions

---

gradle/dependencies.gradle
tooling/rib-intellij-plugin/src/main/java/com/badoo/ribs/plugin/generator/SourceSetDirectoriesProvider.kt

Also downgrade the IJ Runtime version to work fine in AS4.1

Added exception handling in order to work fine in AS4.2+

---

documentation/index.md
documentation/testing/compatibility.md
documentation/testing/integration-tests.md
documentation/testing/preparations.md
documentation/testing/unit-tests.md

Related to https://github.com/badoo/RIBs/pull/303
Would be nice to have test sample app done by newjoiners.

Testing documentation

---

.github/workflows/ci.yml
build.gradle
gradle/dependencies.gradle
libraries/rib-base-test-activity/src/androidTest/java/com/badoo/ribs/test/view/RibsViewRuleTestBase.kt
plugins/build.gradle
tooling/rib-intellij-plugin/build.gradle

Update IntelliJ plugin to resolve sync issues with Kotlin

Update IntelliJ plugin and add mavenCentral to fix assemble check and sync issues

---

libraries/rib-base/src/main/java/com/badoo/ribs/minimal/reactive/Operators.kt
libraries/rib-base/src/test/java/com/badoo/ribs/minimal/reactive/CombineLatestTest.kt
libraries/rib-base/src/test/java/com/badoo/ribs/minimal/reactive/DistinctUntilChangedTest.kt
libraries/rib-base/src/test/java/com/badoo/ribs/minimal/state/StoreTest.kt
libraries/rib-base/src/test/java/com/badoo/ribs/routing/transition/progress/MultiProgressEvaluatorTest.kt

Fixes https://github.com/badoo/RIBs/issues/326
Simple reactive operators are not that simple.

Transition fix

---

libraries/rib-base/src/main/java/com/badoo/ribs/routing/state/feature/Actor.kt
libraries/rib-base/src/test/java/com/badoo/ribs/routing/state/feature/ActorTest.kt

https://github.com/badoo/RIBs/issues/342

Issue 342 - Never ending transition viewless rib fix

---

libraries/rib-base/src/main/java/com/badoo/ribs/routing/source/impl/Pool.kt
libraries/rib-base/src/test/java/com/badoo/ribs/routing/source/impl/PoolTest.kt
libraries/rib-recyclerview/src/main/java/com/badoo/ribs/android/recyclerview/Adapter.kt
libraries/rib-recyclerview/src/main/java/com/badoo/ribs/android/recyclerview/RecyclerViewHostBuilder.kt

Implemented saving and restoring state for Pool.
Fixed issue #344

Implement saving state for pool

---

libraries/rib-base/src/main/java/com/badoo/ribs/routing/state/action/single/ActivateAction.kt
libraries/rib-base/src/main/java/com/badoo/ribs/routing/state/action/single/AddAction.kt
libraries/rib-base/src/main/java/com/badoo/ribs/routing/state/action/single/DeactivateAction.kt
libraries/rib-base/src/main/java/com/badoo/ribs/routing/state/action/single/RemoveAction.kt
libraries/rib-base/src/main/java/com/badoo/ribs/routing/state/feature/RoutingStatePool.kt
libraries/rib-base/src/test/java/com/badoo/ribs/routing/state/RoutingStatePoolTest.kt

Fix view is not attached

---

gradle/dependencies.gradle

Update appTreeUtils version

---

gradle/dependencies.gradle
gradle/utils.gradle
gradle/wrapper/gradle-wrapper.properties
libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/BaseNodesTest.kt
libraries/rib-compose/build.gradle
samples/app/gallery/build.gradle
samples/app/unsplash-client/build.gradle
samples/elements/android-integration/launching-activities/build.gradle
samples/elements/communication/coordinate-multiple/build.gradle
sandbox/build.gradle
sandbox/src/main/java/com/badoo/ribs/sandbox/rib/switcher/SwitcherInteractor.kt

- Updated Jetpack Compose to 1.2.0
- Updated compileSdk to 32 which is needed by compose 1.2.0 (and targetSdk)
- Kotlin updated to 1.7.0
- Updated AGP and gradle
- Updated robolectric to support sdk 32
https://github.com/badoo/RIBs/issues/368

Update compose to 1.2.0 and kotlin to 1.7.0

---

gradle.properties

Update version to 0.35.0

---

libraries/rib-base-test-rx2/src/main/java/com/badoo/ribs/test/rx2/view/RibViewStub.kt
libraries/rib-base-test/src/main/java/com/badoo/ribs/test/view/RibViewStub.kt

Checked with failing test in appyx

Override new view methods in tests

---

documentation/tree-structure-101/providing-dependencies.md

Changed example for providing dependencies documentation.

Review examples in the RIBS documentation

---

gradle.properties

Update version to 0.36.2

---

build.gradle
gradle/dependencies.gradle
gradle/utils.gradle
libraries/rib-base/src/androidTest/java/com/badoo/ribs/test/util/TestActivity.kt
libraries/rib-base/src/main/java/com/badoo/ribs/routing/transition/effect/fade/Fade.kt
libraries/rib-base/src/main/java/com/badoo/ribs/routing/transition/effect/sharedelement/SharedElementTransition.kt
libraries/rib-base/src/main/java/com/badoo/ribs/routing/transition/effect/slide/SlideValueAnimator.kt
libraries/rib-base/src/test/java/com/badoo/ribs/clienthelper/childaware/ChildAwareImplTest.kt
libraries/rib-base/src/test/java/com/badoo/ribs/core/NodePluginNodeLifecycleAwareTest.kt
libraries/rib-base/src/test/java/com/badoo/ribs/core/NodePluginSubtreeChangeAwareTest.kt
libraries/rib-base/src/test/java/com/badoo/ribs/core/NodeTest.kt
libraries/rib-base/src/test/java/com/badoo/ribs/core/lifecycle/CappedLifecycleTest.kt
libraries/rib-base/src/test/java/com/badoo/ribs/core/lifecycle/MinimumCombinedLifecycleTest.kt
libraries/rib-compose/build.gradle
libraries/rib-rx2/src/test/java/com/badoo/ribs/rx2/DisposablePluginTest.kt
libraries/rib-rx2/src/test/java/com/badoo/ribs/rx2/workflows/WorkflowTest.kt
samples/app/gallery/build.gradle
samples/app/unsplash-client/build.gradle
samples/elements/android-integration/launching-activities/build.gradle
samples/elements/communication/coordinate-multiple/build.gradle
sandbox/build.gradle

**Description**: Updating RIBs libraries to match the versions currently used in Appyx as well as MVICore

Updated important libraries to match appyx versions

---

gradle.properties

Increment version in preparation for release.

Updated version to 0.37.0

---

.github/workflows/ci.yml
gradle.properties
libraries/rib-compose/build.gradle
samples/app/gallery/build.gradle
samples/elements/communication/coordinate-multiple/build.gradle
sandbox/build.gradle

**Description**
Fixed publication of libraries using Jetpack Compose and added the local publication to the build step.

Fixed publication of libraries using Jetpack Compose

---

libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/RetainedInstanceStoreTest.kt
libraries/rib-base/src/main/java/com/badoo/ribs/store/RetainedInstanceStore.kt
libraries/rib-base/src/main/java/com/badoo/ribs/store/RetainedInstanceStoreImpl.kt
libraries/rib-base/src/test/java/com/badoo/ribs/store/RetainedInstanceStoreTest.kt

Added mechanism to query retained instance store

Added mechanism to query retained instance store

---

gradle.properties

Update version to 0.39.0

---

gradle/dependencies.gradle
libraries/rib-base-test/src/main/java/com/badoo/ribs/test/CustomisationExt.kt
samples/app/customisations-demo/src/main/java/com/badoo/ribs/samples/customisations/app/AppCustomisations.kt
sandbox/src/main/java/com/badoo/ribs/sandbox/app/AppRibCustomisations.kt
sandbox/src/test/java/com/badoo/ribs/sandbox/rib/menu/MenuRibTest.kt
sandbox/src/test/java/com/badoo/ribs/sandbox/rib/test/MainScreenTest.kt

Updated appyx dependency and did the migration

Update appyx dependency to 1.2.0

---

gradle.properties

Update version to 0.40.1

---

gradle.properties

Update version to 0.40.2

---

jitpack.yml

Cannot publish the next version until this is updated

Changed Jitpack to use JDK17
