badoo/RIBs

- android/app-example/src/main/java/com/badoo/ribs/example/rib/switcher/SwitcherRouter.kt
- android/app-example/src/main/java/com/badoo/ribs/example/rib/switcher/SwitcherView.kt
- android/app-example/src/test/java/com/badoo/ribs/example/rib/test/MainScreenTest.kt
- android/libraries/rib-base/src/main/java/com/badoo/ribs/core/Node.kt
- android/libraries/rib-base/src/main/java/com/badoo/ribs/core/Router.kt
- android/libraries/rib-base/src/main/java/com/badoo/ribs/core/view/RibView.kt
- android/libraries/rib-base/src/test/java/com/badoo/ribs/core/NodeTest.kt
- android/libraries/rib-base/src/test/java/com/badoo/ribs/core/helper/TestView.kt
`getParentViewForChild` method was in `Router` for historical reasons (when view attaching was done manually in `Router`), but conceptually it's in a better place in `RibView`.
Benefits:
- Actually responsibility of `View`, not `Router`
- Don't need to care for `View` null case in `Router`
- Don't need to expose `ViewGroup` fields in specific `View` interface, they can remain an implementation detail + we can avoid having to implement it in all other `View` implementations
> Move getParentViewForChild method to RibView

- android/app-example/src/test/java/com/badoo/ribs/example/rib/switcher/SwitcherRouterTest.kt
- android/app-example/src/test/java/com/badoo/ribs/example/rib/util/TestNode.kt
- android/libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/BaseNodesTest.kt
- android/libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/InitialNodesStateTest.kt
- android/libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/PushOneTest.kt
- android/libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/PushTwoPopOneDefaultTest.kt
- android/libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/PushTwoPopOnePauseAfterPopTest.kt
- android/libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/PushTwoPopOnePauseBeforePopTest.kt
- android/libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/PushTwoPopOnePauseBeforePushTest.kt
- android/libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/PushTwoPopOnePauseBetweenPushesTest.kt
- android/libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/PushTwoPopOnePauseTest.kt
- android/libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/PushTwoPopOneStopAfterPopTest.kt
- android/libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/PushTwoPopOneStopBeforePopTest.kt
- android/libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/PushTwoPopOneStopBeforePushTest.kt
- android/libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/PushTwoPopOneStopBetweenPushesTest.kt
- android/libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/PushTwoPopOneStopStartResumeTest.kt
- android/libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/PushTwoPopOneStopStartTest.kt
- android/libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/PushTwoPopOneStopTest.kt
- android/libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/PushTwoPopOneTest.kt
- android/libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/PushTwoTest.kt
- android/libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/RestartActivityNodesStateTest.kt
- android/libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/RootNodeLifecycleTest.kt
- android/libraries/rib-base/src/androidTest/java/com/badoo/ribs/android/lifecycle/helper/NodeState.kt
- android/libraries/rib-base/src/main/java/com/badoo/ribs/core/Interactor.kt
- android/libraries/rib-base/src/main/java/com/badoo/ribs/core/Node.kt
- android/libraries/rib-base/src/main/java/com/badoo/ribs/core/routing/configuration/action/single/ActivateAction.kt
- android/libraries/rib-base/src/test/java/com/badoo/ribs/core/InteractorTest.kt
- android/libraries/rib-base/src/test/java/com/badoo/ribs/core/NodeTest.kt
- android/libraries/rib-base/src/test/java/com/badoo/ribs/core/helper/TestNode.kt
Implemented in this ticket:
- Moved lifecycle completely from `Interactor`
- `Node` will go through pause & stop when view is detached (technically when in back stack)
- `Node` will go through start & resume when view is attached (technically when most recent in back stack)
- `Node` keeps track of external lifecycle (e.g. hosting `Activity`), so that its state cannot go higher than that of the external (e.g. `Activity` is paused, but `Node` is reattached, it cannot go to resumed)
- child `Nodes` that are created / attached, assume the external lifecycle from their parents (as otherwise they wouldn't know it until next external lifecycle callback)
- tests that cover the above regardless of when the external lifecycle changes while pausing / popping test configurations
Not supported in this …
> Lifecycle improvements

- android/templates/src/main/res/layout/rib_foo_bar.xml
Since ViewImpl is no longer an Android view, it's a mistake that the xml still tried to inflate it. This PR corrects it.
> Change root tag to ConstraintLayout

- android/tooling/rib-intellij-plugin/src/main/resources/META-INF/plugin.xml
> Your plugin has a lot of compatibility problems with build 192.* due to Java functionality was extracted to a separate plugin in IntelliJ IDEA, and if your plugin use classes from the Java part of IntelliJ API you should declare a dependency on com.intellij.modules.java module. Please add this dependency and re-upload your plugin. If you use 'gradle-intellij-plugin', you can add plugins "java" to intellij configuration in your build.gradle file.
>Please see this post https://blog.jetbrains.com/platform/2019/06/java-functionality-extracted-as-a-plugin/
> Add java plugin to fix compatibility issue

- android/templates/release-0.8/src/main/java/com/badoo/ribs/template/rib_with_view/foo_bar/FooBarInteractor.kt
- android/templates/release-0.8/src/main/java/com/badoo/ribs/template/rib_with_view/foo_bar/FooBarRouter.kt
- android/templates/release-0.8/src/main/java/com/badoo/ribs/template/rib_with_view/foo_bar/feature/FooBarFeature.kt
- android/templates/snapshot/src/main/java/com/badoo/ribs/template/rib_with_view/foo_bar/FooBarInteractor.kt
- android/templates/snapshot/src/main/java/com/badoo/ribs/template/rib_with_view/foo_bar/FooBarRouter.kt
- android/templates/snapshot/src/main/java/com/badoo/ribs/template/rib_with_view/foo_bar/feature/FooBarFeature.kt
Following https://github.com/badoo/RIBs/pull/105, make Feature, Interactor and Router classes internal too. They are not exposed by public constructor anymore.
> Make feature, interactor and router internal in template

- android/templates/snapshot/src/main/AndroidManifest.xml
We had this issue while publishing the plugin:
```
> Task :tooling:rib-intellij-plugin:publishPlugin FAILED
Failed to upload plugin: You have not accepted JetBrains Plugin Marketplace agreement.
```
The license has been accepted, now publishing should work
> Update RIBs templates to trigger plugin push

- android/tutorials/tutorial4/README.md
Removed mentioning of HelloWorldRouter from 4th tutorial: [issue](https://github.com/badoo/RIBs/issues/128)
> remove HelloWorldRouter from 4th tutorial

- .github/workflows/ci.yml
- Store Gradle cache for jobs
- Add `org.gradle.parallel=true` Gradle option for build and unit tests
- Use 22, 25, 29 sdk versions for ui test runs
> Store gradle cache for the build job

- android/app-example/src/test/java/com/badoo/ribs/example/rib/switcher/SwitcherRouterTest.kt
- android/libraries/rib-base/src/main/java/com/badoo/ribs/core/Node.kt
- android/libraries/rib-base/src/main/java/com/badoo/ribs/core/builder/BuildContext.kt
- android/libraries/rib-base/src/main/java/com/badoo/ribs/core/routing/action/AddToRecyclerViewRoutingAction.kt
- android/libraries/rib-base/src/main/java/com/badoo/ribs/core/routing/action/AttachRibRoutingAction.kt
- android/libraries/rib-base/src/main/java/com/badoo/ribs/core/routing/action/CompositeRoutingAction.kt
- android/libraries/rib-base/src/main/java/com/badoo/ribs/core/routing/action/DialogRoutingAction.kt
- android/libraries/rib-base/src/main/java/com/badoo/ribs/core/routing/action/InvokeOnCleanUp.kt
- android/libraries/rib-base/src/main/java/com/badoo/ribs/core/routing/action/InvokeOnExecute.kt
- android/libraries/rib-base/src/main/java/com/badoo/ribs/core/routing/action/RoutingAction.kt
- android/libraries/rib-base/src/main/java/com/badoo/ribs/core/routing/configuration/ConfigurationContext.kt
- android/libraries/rib-base/src/main/java/com/badoo/ribs/core/routing/portal/PortalRouter.kt
- android/libraries/rib-base/src/main/java/com/badoo/ribs/dialog/Dialog.kt
- android/libraries/rib-base/src/test/java/com/badoo/ribs/core/RouterTest.kt
- android/libraries/rib-base/src/test/java/com/badoo/ribs/core/routing/configuration/ConfigurationContextTest.kt
- android/libraries/rib-base/src/test/java/com/badoo/ribs/core/routing/configuration/ConfigurationFeatureTest.kt
- android/libraries/rib-base/src/test/java/com/badoo/ribs/core/routing/portal/PortalRouterTest.kt
- android/tutorials/tutorial2/src/main/java/com/badoo/ribs/tutorials/tutorial2/app/RootActivity.kt
1. Moves the responsibility of creating `BuildContext` object one level deeper from `RoutingAction`, down to `RoutingAction` invocation.
2. Adds contract that `RoutingAction` reports the number of `Node`s it intends to build. Framework guarantees to pass that many objects. (This same mechanism existed with `Bundle`s so far, only implicitly, and without test coverage that it does indeed work as expected).
First point will also make it easier to add customisation into `BuildContext` by framework as compared to individual `RoutingActions`, which shouldn't have to do anything with it.
> Call RoutingActions with BuildContext

- android/app-example/src/test/java/com/badoo/ribs/example/rib/switcher/SwitcherWorkflowTest.kt
- android/libraries/rib-base/src/main/java/com/badoo/ribs/core/Node.kt
- android/libraries/rib-base/src/main/java/com/badoo/ribs/core/builder/BuildParams.kt
- android/libraries/rib-base/src/main/java/com/badoo/ribs/core/exception/RootNodeAttachedAsChildException.kt
- android/libraries/rib-base/src/test/java/com/badoo/ribs/core/LifecycleManagerTest.kt
- android/libraries/rib-base/src/test/java/com/badoo/ribs/core/NodeTest.kt
- android/libraries/rib-base/src/test/java/com/badoo/ribs/core/helper/AnyConfiguration.kt
- android/libraries/rib-base/src/test/java/com/badoo/ribs/core/helper/TestBuildParams.kt
**Description**: When a node tries to attach another child node, if the child node is built with a Root BuildContext, we should raise a non-fatal error as this is a client-side misconfiguration (Root BuildContext should be used at actual roots at integration point).
**Related issue(s)**: #159
> Attaching a child node built with root BuildContext should raise an error.

- app-example/build.gradle
- gradle/utils.gradle
- libraries/rib-base-test-activity/build.gradle
- libraries/rib-base-test/build.gradle
- libraries/rib-base/build.gradle
- libraries/rib-compose/build.gradle
- libraries/rib-debug-utils/build.gradle
- libraries/rib-portal-rx/build.gradle
- libraries/rib-portal/build.gradle
- libraries/rib-recyclerview/build.gradle
- libraries/rib-rx/build.gradle
- sandbox-compose-placeholder/build.gradle
- sandbox-compose/build.gradle
- sandbox/build.gradle
- tutorials/tutorial1/build.gradle
- tutorials/tutorial2/build.gradle
- tutorials/tutorial3/build.gradle
- tutorials/tutorial4/build.gradle
- tutorials/tutorial5/build.gradle
Kotlin compiler still uses 1.6 target, use 1.8 instead.
It allow us to use 1.8 compiled external dependencies (e.g. `androidx-ktx` libraries).
> Set JVM 1.8 target for Kotlin

- libraries/rib-base/src/main/java/com/badoo/ribs/android/dialog/Dialog.kt
- libraries/rib-base/src/main/java/com/badoo/ribs/android/dialog/DialogExtensions.kt
- sandbox/detekt-baseline.xml
- sandbox/src/androidTest/java/com/badoo/ribs/sandbox/rib/dialog_example/DialogExampleTest.kt
- sandbox/src/main/java/com/badoo/ribs/sandbox/rib/dialog_example/DialogExampleInteractor.kt
- sandbox/src/main/java/com/badoo/ribs/sandbox/rib/dialog_example/DialogExampleView.kt
- sandbox/src/main/java/com/badoo/ribs/sandbox/rib/dialog_example/dialog/Dialogs.kt
- sandbox/src/main/java/com/badoo/ribs/sandbox/rib/dialog_example/dialog/RibDialog.kt
- sandbox/src/main/java/com/badoo/ribs/sandbox/rib/dialog_example/dialog/ThemeDialog.kt
- sandbox/src/main/java/com/badoo/ribs/sandbox/rib/dialog_example/dialog/ThemedDialog.kt
- sandbox/src/main/java/com/badoo/ribs/sandbox/rib/dialog_example/routing/DialogExampleRouter.kt
- sandbox/src/main/res/layout/rib_dialog_example.xml
- sandbox/src/main/res/values/colors.xml
- sandbox/src/main/res/values/strings.xml
- sandbox/src/main/res/values/styles.xml
**Description**: Add a nullable `themeResId` in `Dialog` abstraction class for allowing library users to apply a specific style into their `AlertDialogs`. An example can be found in Dialog tab in `sandbox` app.
This `themeResId` will allow to change text colours, text sizes, background, fonts, etc.
> Add theme to dialogs

- libraries/rib-base/src/main/java/com/badoo/ribs/core/customisation/RibCustomisationDirectoryImpl.kt
**Description**: `RibCustomisationDirectoryImpl` had an extra class reference in the removed function that was unnecessary and unused.
> Remove unnecessary class reference from RibCustomisationDirectoryImpl

- libraries/rib-base/src/main/java/com/badoo/ribs/routing/router/Router.kt
- libraries/rib-base/src/test/java/com/badoo/ribs/core/RouterTest.kt
After restoration (e.g. DKA), routing re-initialisation happened earlier than proper references were set. This fixes that.
> Init routing only after rib/node references are set

- libraries/rib-base/src/main/java/com/badoo/ribs/routing/source/backstack/BackStack.kt
Active config is not properly retrieved
> Fix activeConfiguration being set up forever with the first state

- templates/snapshot/src/main/java/com/badoo/ribs/template/leaf/foo_bar/FooBarView.kt
- templates/snapshot/src/main/java/com/badoo/ribs/template/leaf_view_only/foo_bar/FooBarView.kt
- templates/snapshot/src/main/java/com/badoo/ribs/template/node/foo_bar/FooBarView.kt
Allows easier usage in tests:
```kotlin
ProfileBuilderRelationshipEndScreen.Customisation(viewFactory = { { stubView } })
```
> Use fun interfaces for view factories in template

- build.gradle
- gradle/code-coverage.gradle
- gradle/dependencies.gradle
- libraries/rib-base/build.gradle
This PR consists in adding code coverage support with Jacoco to the project.
It adds the 3 following Gradle tasks under the `code coverage` group:
**Example**:
> Add support for code coverage

- .github/workflows/ci.yml
- gradle.properties
We are still using `cache@v1`. Upgrading to v2 can improve our CI stability (most of the failures because of cache step failure).
Applied [recommended setup](https://github.com/actions/cache/blob/main/examples.md#java---gradle) with `useCompose` split.
> Use cache@v2

- libraries/rib-compose/src/main/java/com/badoo/ribs/compose/ComposeRibView.kt
- sandbox-compose/build.gradle
- sandbox-compose/src/main/java/com/badoo/ribs/sandbox/rib/compose_leaf/ComposeLeaf.kt
- sandbox-compose/src/main/java/com/badoo/ribs/sandbox/rib/compose_leaf/ComposeLeafBuilder.kt
- sandbox-compose/src/main/java/com/badoo/ribs/sandbox/rib/compose_leaf/ComposeLeafInteractor.kt
- sandbox-compose/src/main/java/com/badoo/ribs/sandbox/rib/compose_leaf/ComposeLeafView.kt
- sandbox-compose/src/main/java/com/badoo/ribs/sandbox/rib/compose_parent/ComposeParentBuilder.kt
- sandbox-compose/src/main/java/com/badoo/ribs/sandbox/rib/compose_parent/ComposeParentInteractor.kt
- sandbox-compose/src/main/java/com/badoo/ribs/sandbox/rib/compose_parent/ComposeParentView.kt
- sandbox-compose/src/main/java/com/badoo/ribs/sandbox/rib/compose_parent/routing/ComposeParentRouter.kt
> Fix compose view detach

- libraries/rib-base/src/main/java/com/badoo/ribs/routing/state/action/single/ActivateAction.kt
- libraries/rib-base/src/main/java/com/badoo/ribs/routing/state/action/single/DeactivateAction.kt
- libraries/rib-base/src/main/java/com/badoo/ribs/routing/state/action/single/Ext.kt
Symptom: viewless containers might have children with views; they're not animated in.
Fix in this ticket: recursively find transition targets from children if own Node is viewless.
> Fix transitions for viewless containers

- app-example/src/main/java/com/badoo/ribs/example/feed_container/FeedContainerInteractor.kt
- app-example/src/main/java/com/badoo/ribs/example/logged_in_container/LoggedInContainerInteractor.kt
- app-example/src/main/java/com/badoo/ribs/example/logged_out_container/LoggedOutContainerInteractor.kt
- libraries/rib-base/src/main/java/com/badoo/ribs/clienthelper/childaware/ChildAware.kt
- libraries/rib-base/src/main/java/com/badoo/ribs/clienthelper/childaware/ChildAwareCallbackInfo.kt
- libraries/rib-base/src/main/java/com/badoo/ribs/clienthelper/childaware/ChildAwareDSL.kt
- libraries/rib-base/src/main/java/com/badoo/ribs/clienthelper/childaware/ChildAwareExt.kt
- libraries/rib-base/src/main/java/com/badoo/ribs/clienthelper/childaware/ChildAwareImpl.kt
- libraries/rib-base/src/main/java/com/badoo/ribs/clienthelper/childaware/ChildAwareScope.kt
- libraries/rib-base/src/main/java/com/badoo/ribs/clienthelper/childaware/LifecycleExt.kt
- libraries/rib-base/src/test/java/com/badoo/ribs/clienthelper/childaware/ChildAwareImplTest.kt
- libraries/rib-base/src/test/java/com/badoo/ribs/core/lifecycle/MinimumCombinedLifecycleTest.kt
- libraries/rib-base/src/test/java/com/badoo/ribs/core/lifecycle/TestLifecycle.kt
- libraries/rib-mvicore/src/main/java/com/badoo/ribs/mvicore/ChildAwareExt.kt
- sandbox/src/main/java/com/badoo/ribs/sandbox/rib/switcher/SwitcherInteractor.kt
The following code will:
1. Produce memory leak of `view`, because it is captured by callback, which is not removed later.
2. Be invoked twice for old and new instance of `view`.
```kotlin
override fun onViewCreated(view: View, lifecycle: Lifecycle) {
whenChildAttached { child, commonLifecycle ->
commonLifecycle.createDestroy { bind(view to child) }
}
}
```
PR adds destroyed state checks (API usage correctness) and callback removal when parent lifecycle is destroyed.
TODO: Remove default lifecycle
> Remove child aware callbacks when parent lifecycle is destroyed

- samples/transition-animations/src/main/java/com/badoo/ribs/samples/transitionanimations/rib/parent/routing/ParentTransitionHandler.kt
In the current implementation, the animations look weird when going back. This PR makes them look the same as the animations look when going forward but in reverse.
| Before | After |
|-------|------|
| ![back-animation-bad](https://user-images.githubusercontent.com/6322898/120648036-1fe02b00-c473-11eb-979b-9e3f6f60ef69.gif) | ![back-animation-good](https://user-images.githubusercontent.com/6322898/120648061-25d60c00-c473-11eb-85de-83af5597d002.gif) |
> Fixed animations in transition animations example when pressing back

- libraries/rib-base-test-activity/src/androidTest/java/com/badoo/ribs/test/RibsRuleTestBase.kt
- libraries/rib-base-test-activity/src/androidTest/java/com/badoo/ribs/test/Utils.kt
1 second might be not enough on CPU overloaded virtual machine.
> Replace Thread.sleep with waitFor

- libraries/rib-compose/src/main/java/com/badoo/ribs/compose/ComposeRibView.kt
If you access in your composable function properties or classes defined in your `View` class which extends `ComposeRibView` then this class will be added to your composable function as a parameter. Right now extensions of `ComposeRibView` are unstable not allowing to skip execution 
https://github.com/badoo/RIBs/issues/372
> Make ComposeRibView.kt stable which is used as a receiver for some composable function

- gradle/dependencies.gradle
- libraries/rib-base/build.gradle
- libraries/rib-base/src/main/java/com/badoo/ribs/core/Node.kt
- libraries/rib-base/src/main/java/com/badoo/ribs/core/lifecycle/LifecycleManager.kt
- libraries/rib-base/src/main/java/com/badoo/ribs/core/view/AndroidRibView.kt
- libraries/rib-base/src/main/java/com/badoo/ribs/core/view/AndroidRibView2.kt
- libraries/rib-base/src/main/java/com/badoo/ribs/core/view/RibView.kt
- libraries/rib-base/src/test/java/com/badoo/ribs/core/NodeTest.kt
- libraries/rib-compose/src/main/java/com/badoo/ribs/compose/ComposeRibView.kt
- samples/app/gallery/src/main/java/com/badoo/ribs/samples/gallery/rib/android/container/AndroidContainerView.kt
- samples/app/gallery/src/main/java/com/badoo/ribs/samples/gallery/rib/android/picker/AndroidPickerView.kt
- samples/app/gallery/src/main/java/com/badoo/ribs/samples/gallery/rib/communication/container/CommunicationContainerView.kt
- samples/app/gallery/src/main/java/com/badoo/ribs/samples/gallery/rib/communication/picker/CommunicationPickerView.kt
- samples/app/gallery/src/main/java/com/badoo/ribs/samples/gallery/rib/other/container/OtherContainerView.kt
- samples/app/gallery/src/main/java/com/badoo/ribs/samples/gallery/rib/other/picker/OtherPickerView.kt
- samples/app/gallery/src/main/java/com/badoo/ribs/samples/gallery/rib/root/container/RootContainerView.kt
- samples/app/gallery/src/main/java/com/badoo/ribs/samples/gallery/rib/root/picker/RootPickerView.kt
- samples/app/gallery/src/main/java/com/badoo/ribs/samples/gallery/rib/routing/routing_container/RoutingContainerView.kt
- samples/app/gallery/src/main/java/com/badoo/ribs/samples/gallery/rib/routing/routing_picker/RoutingPickerView.kt
- samples/elements/android-integration/permissions/build.gradle
- sandbox/src/main/java/com/badoo/ribs/sandbox/rib/compose_leaf/ComposeLeafView.kt
- sandbox/src/main/java/com/badoo/ribs/sandbox/rib/compose_parent/ComposeParentView.kt
- Provide `SavedStateRegistry` and `LifecycleOwner` per RIB view so Compose or any other views can use it.
- Introduce `AndroidRibView2` to keep compatibility with old code.
https://user-images.githubusercontent.com/9081555/192304144-d28d5d1a-43fe-46f5-a533-22e9bc76e1fe.mp4
> Provide ViewTreeLifecycleOwner and ViewTreeSavedStateRegistryOwner

- libraries/rib-base-test-activity/src/main/java/com/badoo/ribs/test/view/RibsViewActivity.kt
- sandbox/src/main/java/com/badoo/ribs/sandbox/rib/menu/MenuView.kt
`AndroidRibView2` uses `savedStateRegistry`. In RIBs view test `savedStateRegistry` state must be restored to avoid crash:
```
java.lang.IllegalStateException: You can consumeRestoredStateForKey only after super.onCreate of corresponding component
at androidx.savedstate.SavedStateRegistry.consumeRestoredStateForKey(SavedStateRegistry.kt:72)
at androidx.savedstate.Recreator.onStateChanged(Recreator.kt:34)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
at …
```
> Restore view state in RibsViewActivity.kt

- libraries/rib-base/src/main/java/com/badoo/ribs/android/integrationpoint/FragmentIntegrationPoint.kt
In ActivityIntegrationPoint we use `NOT` of `activity.isChangingConfigurations` which is correct, since the activity is _not_ finishing i.e. is recreating when it is true.
However, in FragmentIntegrationPoint we use it without the negation, which means it thinks it is finishing when it is recreating and thinks it is not finishing when it is actually finishing.
This PR fixes it.
> Add negation for isChangingConfigurations in FragmentIntegrationPoint

- libraries/rib-base-test/src/main/java/com/badoo/ribs/test/CustomisationExt.kt
`toDirectory()` wasn't working properly with lazy customisations as it was always using `NodeCustomisation::class` as a key
> Fix toDirectory() ext method to work property with lazy

- libraries/rib-base/src/main/java/com/badoo/ribs/android/dialog/DialogExtensions.kt
I am marking the alert dialog's title as heading for accessibility purposes
> Alert Dialog's title marked as heading (for accessibility purposes)

- gradle.properties
- libraries/rib-base/src/main/java/com/badoo/ribs/core/Node.kt
- libraries/rib-base/src/main/java/com/badoo/ribs/core/plugin/Plugin.kt
- libraries/rib-base/src/main/java/com/badoo/ribs/util/RIBs.kt
Added 'global plugins' to enable developers to introduce diagnostic tools without needing to find the RIB within the view hierarchy
> Introduced global plugins, added GlobalNodeLifecycleAware and expose view

- gradle.properties
- libraries/rib-base/src/main/java/com/badoo/ribs/routing/source/backstack/BackStack.kt
- samples/app/unsplash-client/src/test/java/com/badoo/ribs/example/root/RootInteractorAuthStateTest.kt
- sandbox/src/test/java/com/badoo/ribs/sandbox/rib/switcher/SwitcherInteractorTest.kt
After attempting to use 0.40.3 I noticed Mockito was failing due to mock `BackStack` I then remembered that previously some tests were commented out that were also failing for this reason.
This issue only occurs when the library is compiled using JDK 17. By making a minor tweak to the source code we can eliminate the issue.
The error is as follows `Mismatch of count of formal and actual type arguments in constructor of com.badoo.ribs.routing.source.backstack.BackStack$store$1: 0 formal argument(s) 1 actual argument(s)`
The full error is below:
```
Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [interface com.badoo.ribs.routing.source.RoutingSource, interface com.badoo.ribs.core.plugin.Plugin, interface …
```
> Fix backstack JDK 17 byte code
